name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON wallets
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_JSONS: ./wallets.json
          INPUT_SCHEMA: ./schema.wallets.json
      - name: Validate JSON list
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_JSONS: ./list.json
          INPUT_SCHEMA: ./schema.list.json

